doc: add minutes for meetingf 19 Apr 2017
nodejs/CTC pull request #108
Opened 2017-04-20 14:51 UTC by mhdawson

2017-04-20 15:15 UTC, jasnell approved these changes

2017-04-20 20:55 UTC, Trott approved these changes
LGTM. Thanks for taking the minutes, @mhdawson!

2017-04-20 21:32 UTC, joshgav commented
Thanks @mhdawson! LGTM.

2017-04-20 21:34 UTC, joshgav requested changes

2017-04-20 21:34 UTC, joshgav commented on meetings/2017-04-19.md
> +* **Audio recording**: <https://www.youtube.com/watch?v=S69FsEpLacc>
This is the previous week's meeting - this one is https://www.youtube.com/watch?v=DemuVw4XRHQ

2017-04-20 21:34 UTC, joshgav commented on meetings/2017-04-19.md
> +* **GitHub Issue**: [CTC#98](https://github.com/nodejs/CTC/issues/105)
Oops, contradiction between text and link.

2017-04-20 21:34 UTC, joshgav commented on meetings/2017-04-19.md
> +  when Josh can frame the conversation.
sounds good :)

2017-04-25 14:58 UTC, mhdawson commented on meetings/2017-04-19.md
> +* **Audio recording**: <https://www.youtube.com/watch?v=S69FsEpLacc>
Fixed

2017-04-25 14:59 UTC, mhdawson commented on meetings/2017-04-19.md
> +* **GitHub Issue**: [CTC#98](https://github.com/nodejs/CTC/issues/105)
fixed

2017-04-25 15:01 UTC, mhdawson commented
@joshgav pushed commit to address comments.

2017-04-26 21:03 UTC, joshgav approved these changes

2017-04-27 15:15 UTC, mhdawson commented
Landed as 90dae984ab5582561731ab1c23d8f24e2a782c9a

2017-04-27 15:15 UTC, closed without merging